export type AssetStatus = "Available" | "Allocated" | "Maintenance" | "Reserved" | "Lost" | "Disposed" | "Retired";
export type AssetCondition = "Excellent" | "Good" | "Fair" | "Poor" | "New";
export type AssetCategory = "Electronics" | "Furniture" | "Vehicles" | "Network" | "IT Equipment" | "AV Equipment";

export interface Asset {
  id: string;
  tag: string;
  name: string;
  category: AssetCategory;
  serialNumber: string;
  department: string;
  location: string;
  status: AssetStatus;
  condition: AssetCondition;
  purchaseDate: string;
  purchaseCost: number;
  warrantyExpiry: string;
  assignedEmployee?: string;
  description?: string;
  bookable: boolean;
}

export const mockAssets: Asset[] = [
  {
    id: "a1",
    tag: "AF-0012",
    name: "Dell XPS 15 Laptop",
    category: "Electronics",
    serialNumber: "SN-99821-F24",
    department: "Engineering",
    location: "HQ Floor 3",
    status: "Allocated",
    condition: "Excellent",
    purchaseDate: "2023-01-15",
    purchaseCost: 2100,
    warrantyExpiry: "2026-01-15",
    assignedEmployee: "Aditi Rao",
    bookable: false,
    description: "High-performance developer laptop.",
  },
  {
    id: "a2",
    tag: "AF-0062",
    name: "Epson Pro G7905U Projector",
    category: "AV Equipment",
    serialNumber: "SN-55432-P09",
    department: "Facilities",
    location: "HQ Floor 2",
    status: "Maintenance",
    condition: "Good",
    purchaseDate: "2022-04-10",
    purchaseCost: 3500,
    warrantyExpiry: "2025-04-10",
    bookable: true,
    description: "Main conference room projector. Lamp needs replacement.",
  },
  {
    id: "a3",
    tag: "AF-0201",
    name: "Herman Miller Aeron Chair",
    category: "Furniture",
    serialNumber: "SN-00123-C01",
    department: "Warehouse",
    location: "Storage Room B",
    status: "Available",
    condition: "Fair",
    purchaseDate: "2021-08-22",
    purchaseCost: 1200,
    warrantyExpiry: "2033-08-22",
    bookable: false,
    description: "Ergonomic office chair. Slight wear on armrests.",
  },
  {
    id: "a4",
    tag: "AF-0554",
    name: "MacBook Pro 16 M2",
    category: "Electronics",
    serialNumber: "SN-88721-M02",
    department: "Marketing",
    location: "Remote",
    status: "Allocated",
    condition: "Excellent",
    purchaseDate: "2023-11-05",
    purchaseCost: 2800,
    warrantyExpiry: "2026-11-05",
    assignedEmployee: "Sarah Jenkins",
    bookable: false,
  },
  {
    id: "a5",
    tag: "AF-0891",
    name: "Cisco Catalyst 9300 Switch",
    category: "Network",
    serialNumber: "SN-22341-S90",
    department: "IT Ops",
    location: "Server Room A",
    status: "Allocated",
    condition: "Good",
    purchaseDate: "2022-09-12",
    purchaseCost: 4500,
    warrantyExpiry: "2027-09-12",
    bookable: false,
  },
  {
    id: "a6",
    tag: "AF-1023",
    name: "Sony Alpha a7 IV Camera",
    category: "AV Equipment",
    serialNumber: "SN-77123-C10",
    department: "Marketing",
    location: "Media Studio",
    status: "Available",
    condition: "New",
    purchaseDate: "2024-02-15",
    purchaseCost: 2500,
    warrantyExpiry: "2027-02-15",
    bookable: true,
  },
  {
    id: "a7",
    tag: "AF-1105",
    name: "Dell UltraSharp 27 Monitor",
    category: "IT Equipment",
    serialNumber: "SN-33451-M11",
    department: "Engineering",
    location: "HQ Floor 3",
    status: "Allocated",
    condition: "Good",
    purchaseDate: "2022-01-20",
    purchaseCost: 450,
    warrantyExpiry: "2025-01-20",
    assignedEmployee: "Aditi Rao",
    bookable: false,
  },
  {
    id: "a8",
    tag: "AF-1142",
    name: "Logitech MX Master 3 Mouse",
    category: "IT Equipment",
    serialNumber: "SN-99811-M33",
    department: "Warehouse",
    location: "Storage Room A",
    status: "Available",
    condition: "New",
    purchaseDate: "2024-05-10",
    purchaseCost: 99,
    warrantyExpiry: "2025-05-10",
    bookable: false,
  },
  {
    id: "a9",
    tag: "AF-1205",
    name: "Ford Transit Connect Van",
    category: "Vehicles",
    serialNumber: "VIN-4F239847293",
    department: "Facilities",
    location: "Parking Bay 4",
    status: "Maintenance",
    condition: "Fair",
    purchaseDate: "2020-03-15",
    purchaseCost: 28000,
    warrantyExpiry: "2025-03-15",
    bookable: true,
    description: "Scheduled for regular 50k miles service.",
  },
  {
    id: "a10",
    tag: "AF-1334",
    name: "Standing Desk - FlexiSpot",
    category: "Furniture",
    serialNumber: "SN-33499-D02",
    department: "Finance",
    location: "HQ Floor 1",
    status: "Allocated",
    condition: "Excellent",
    purchaseDate: "2023-06-11",
    purchaseCost: 650,
    warrantyExpiry: "2028-06-11",
    assignedEmployee: "Michael Chang",
    bookable: false,
  },
  {
    id: "a11",
    tag: "AF-1402",
    name: "Lenovo ThinkPad X1 Carbon",
    category: "Electronics",
    serialNumber: "SN-55611-T99",
    department: "IT Ops",
    location: "HQ Floor 2",
    status: "Reserved",
    condition: "Good",
    purchaseDate: "2022-11-20",
    purchaseCost: 1800,
    warrantyExpiry: "2025-11-20",
    bookable: false,
    description: "Reserved for new hire starting next Monday.",
  },
  {
    id: "a12",
    tag: "AF-1455",
    name: "Apple iPad Pro 12.9",
    category: "Electronics",
    serialNumber: "SN-77822-I01",
    department: "Marketing",
    location: "Remote",
    status: "Lost",
    condition: "Poor",
    purchaseDate: "2021-09-05",
    purchaseCost: 1100,
    warrantyExpiry: "2022-09-05",
    assignedEmployee: "David Chen",
    bookable: false,
    description: "Reported lost during transit.",
  },
  {
    id: "a13",
    tag: "AF-1560",
    name: "Steelcase Leap V2 Chair",
    category: "Furniture",
    serialNumber: "SN-11233-S09",
    department: "Engineering",
    location: "HQ Floor 3",
    status: "Allocated",
    condition: "Good",
    purchaseDate: "2022-02-18",
    purchaseCost: 950,
    warrantyExpiry: "2034-02-18",
    assignedEmployee: "Aditi Rao",
    bookable: false,
  },
  {
    id: "a14",
    tag: "AF-1601",
    name: "Fortinet FortiGate 100F",
    category: "Network",
    serialNumber: "SN-99011-F00",
    department: "IT Ops",
    location: "Server Room A",
    status: "Allocated",
    condition: "Excellent",
    purchaseDate: "2023-12-01",
    purchaseCost: 3200,
    warrantyExpiry: "2026-12-01",
    bookable: false,
  },
  {
    id: "a15",
    tag: "AF-1772",
    name: "DJI Mavic 3 Pro Drone",
    category: "AV Equipment",
    serialNumber: "SN-55677-D33",
    department: "Marketing",
    location: "Media Studio",
    status: "Reserved",
    condition: "New",
    purchaseDate: "2024-04-20",
    purchaseCost: 2200,
    warrantyExpiry: "2025-04-20",
    bookable: true,
  },
  {
    id: "a16",
    tag: "AF-1823",
    name: "HP LaserJet Pro M404n",
    category: "IT Equipment",
    serialNumber: "SN-33411-P22",
    department: "Finance",
    location: "HQ Floor 1",
    status: "Disposed",
    condition: "Poor",
    purchaseDate: "2019-05-15",
    purchaseCost: 300,
    warrantyExpiry: "2020-05-15",
    bookable: false,
    description: "Paper jam issue, cheaper to replace than repair.",
  },
  {
    id: "a17",
    tag: "AF-1904",
    name: "Conference Table - 12 Seater",
    category: "Furniture",
    serialNumber: "SN-88711-T55",
    department: "Facilities",
    location: "Boardroom A",
    status: "Allocated",
    condition: "Excellent",
    purchaseDate: "2023-01-10",
    purchaseCost: 4500,
    warrantyExpiry: "2028-01-10",
    bookable: false,
  },
  {
    id: "a18",
    tag: "AF-1955",
    name: "Samsung 65\" QLED Display",
    category: "AV Equipment",
    serialNumber: "SN-44522-S65",
    department: "Facilities",
    location: "Boardroom A",
    status: "Allocated",
    condition: "Good",
    purchaseDate: "2023-01-12",
    purchaseCost: 1200,
    warrantyExpiry: "2026-01-12",
    bookable: false,
  },
  {
    id: "a19",
    tag: "AF-2011",
    name: "Toyota Tacoma Pickup",
    category: "Vehicles",
    serialNumber: "VIN-9T485739845",
    department: "Facilities",
    location: "Parking Bay 2",
    status: "Available",
    condition: "Good",
    purchaseDate: "2021-08-05",
    purchaseCost: 35000,
    warrantyExpiry: "2026-08-05",
    bookable: true,
  },
  {
    id: "a20",
    tag: "AF-2134",
    name: "Mac Studio M2 Max",
    category: "Electronics",
    serialNumber: "SN-99888-M11",
    department: "Marketing",
    location: "Media Studio",
    status: "Allocated",
    condition: "Excellent",
    purchaseDate: "2023-10-15",
    purchaseCost: 1999,
    warrantyExpiry: "2026-10-15",
    assignedEmployee: "Sana Iqbal",
    bookable: false,
  },
  {
    id: "a21",
    tag: "AF-2205",
    name: "Ubiquiti UniFi AP AC Pro",
    category: "Network",
    serialNumber: "SN-11222-U00",
    department: "IT Ops",
    location: "HQ Floor 3",
    status: "Allocated",
    condition: "Good",
    purchaseDate: "2021-11-22",
    purchaseCost: 150,
    warrantyExpiry: "2024-11-22",
    bookable: false,
  },
  {
    id: "a22",
    tag: "AF-2256",
    name: "Ergotron Dual Monitor Arm",
    category: "Furniture",
    serialNumber: "SN-77655-E12",
    department: "Engineering",
    location: "HQ Floor 3",
    status: "Allocated",
    condition: "Excellent",
    purchaseDate: "2023-05-19",
    purchaseCost: 350,
    warrantyExpiry: "2033-05-19",
    assignedEmployee: "Aditi Rao",
    bookable: false,
  },
  {
    id: "a23",
    tag: "AF-2301",
    name: "Yamaha MG10XU Audio Mixer",
    category: "AV Equipment",
    serialNumber: "SN-44511-Y99",
    department: "Marketing",
    location: "Storage Room B",
    status: "Available",
    condition: "Fair",
    purchaseDate: "2020-12-01",
    purchaseCost: 220,
    warrantyExpiry: "2021-12-01",
    bookable: true,
  },
  {
    id: "a24",
    tag: "AF-2412",
    name: "APC Smart-UPS 1500VA",
    category: "IT Equipment",
    serialNumber: "SN-22133-A55",
    department: "IT Ops",
    location: "Server Room A",
    status: "Maintenance",
    condition: "Good",
    purchaseDate: "2021-07-10",
    purchaseCost: 550,
    warrantyExpiry: "2024-07-10",
    bookable: false,
    description: "Battery replacement required.",
  },
  {
    id: "a25",
    tag: "AF-2555",
    name: "Google Pixel 8 Pro",
    category: "Electronics",
    serialNumber: "SN-99877-G01",
    department: "Engineering",
    location: "Remote",
    status: "Retired",
    condition: "Poor",
    purchaseDate: "2021-04-11",
    purchaseCost: 999,
    warrantyExpiry: "2022-04-11",
    bookable: false,
    description: "Screen cracked, device retired.",
  }
];
